"use client";

import { useState, useEffect } from "react";
import { useBillingStore } from "../../../store/billing";
import { Database, Plus, FileText, Search, UploadCloud, Trash2, ArrowLeft, Presentation, FileJson, Image as ImageIcon, MonitorPlay, FileArchive, X, GitBranch, FolderUp, RefreshCw, Network } from "lucide-react";
import { PanelGroup, Panel, PanelResizeHandle } from "react-resizable-panels";
import Link from "next/link";
import ReactMarkdown from "react-markdown";
import ignore from 'ignore';

const UNIVERSAL_IGNORES = [
  // Version Control & IDE
  '.git', '.svn', '.hg', '.idea', '.vscode', '.DS_Store',
  
  // Build folders & Caches
  'node_modules', '.next', 'dist', 'build', 'out', '.nuxt', '.cache', 
  '.gradle', '.dart_tool', 'venv', '__pycache__', '.pytest_cache', 
  'target', 'bin', 'obj', 'Pods', 'DerivedData', 'coverage', '.expo',
  
  // Lock files
  'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'bun.lockb',
  'Cargo.lock', 'Gemfile.lock', 'composer.lock', 'pubspec.lock', 'Podfile.lock', 'mix.lock',

  // Autogenerated Code & Maps
  '*.g.dart', '*.freezed.dart', '*.mocks.dart', '*.pb.go', '*.pb.cc', '*.designer.cs',
  '*.min.js', '*.min.css', '*.map',

  // Media & Binaries
  '*.mp4', '*.mov', '*.webm', '*.mp3', '*.wav',
  '*.png', '*.jpg', '*.jpeg', '*.gif', '*.webp', '*.svg', '*.ico',
  '*.woff', '*.woff2', '*.ttf', '*.eot',
  '*.riv', '*.lottie', '*.zip', '*.tar', '*.gz', '*.rar', '*.7z',
  '*.exe', '*.dll', '*.so', '*.dylib', '*.bin', '*.iso'
];

function formatBytes(bytes: number, decimals = 1) {
  if (!+bytes) return '0 Bytes';
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(dm))} ${sizes[i]}`;
}

function getFilePriorityScore(filename: string): number {
  const ext = filename.split('.').pop()?.toLowerCase() || '';
  if (['ts', 'tsx', 'js', 'jsx', 'dart', 'py', 'go', 'rs', 'java', 'kt', 'swift', 'cpp', 'c', 'h', 'cs', 'php', 'rb', 'sql'].includes(ext)) return 10;
  if (['md', 'txt', 'json', 'yaml', 'yml', 'xml', 'html', 'css', 'scss', 'less', 'toml'].includes(ext)) return 5;
  return 1;
}

function formatTimeAgo(dateString: string) {
  if (!dateString) return 'Just now';
  const date = new Date(dateString);
  const now = new Date();
  const diffInSeconds = Math.floor((now.getTime() - date.getTime()) / 1000);
  
  if (diffInSeconds < 60) return `${diffInSeconds}s ago`;
  const diffInMinutes = Math.floor(diffInSeconds / 60);
  if (diffInMinutes < 60) return `${diffInMinutes}m ago`;
  const diffInHours = Math.floor(diffInMinutes / 60);
  if (diffInHours < 24) return `${diffInHours}h ago`;
  const diffInDays = Math.floor(diffInHours / 24);
  if (diffInDays < 7) return `${diffInDays}d ago`;
  const diffInWeeks = Math.floor(diffInDays / 7);
  return `${diffInWeeks}w ago`;
}

const getKbColors = (color: string) => {
  const map: Record<string, string> = {
    'fuchsia': 'text-fuchsia-100 bg-fuchsia-500',
    'blue': 'text-blue-100 bg-blue-500',
    'orange': 'text-orange-100 bg-orange-500',
    'emerald': 'text-emerald-100 bg-emerald-500',
    'violet': 'text-violet-100 bg-violet-500',
    'rose': 'text-rose-100 bg-rose-500',
  };
  return map[color] || map['fuchsia'];
};

const getFileIcon = (type: string) => {
  const t = type.toLowerCase();
  if (['pdf'].includes(t)) return <FileText className="w-3.5 h-3.5 text-rose-400" />;
  if (['pptx', 'ppt'].includes(t)) return <Presentation className="w-3.5 h-3.5 text-orange-400" />;
  if (['docx', 'doc'].includes(t)) return <FileText className="w-3.5 h-3.5 text-blue-400" />;
  if (['xlsx', 'xls', 'csv'].includes(t)) return <FileJson className="w-3.5 h-3.5 text-emerald-400" />;
  if (['png', 'jpg', 'jpeg', 'gif', 'webp'].includes(t)) return <ImageIcon className="w-3.5 h-3.5 text-fuchsia-400" />;
  if (['mp4', 'mov', 'webm'].includes(t)) return <MonitorPlay className="w-3.5 h-3.5 text-purple-400" />;
  if (['zip', 'rar', 'tar'].includes(t)) return <FileArchive className="w-3.5 h-3.5 text-zinc-400" />;
  return <FileText className="w-3.5 h-3.5 text-violet-400" />;
};

const getFileBadgeColors = (type: string) => {
  const t = type.toLowerCase();
  if (['pdf'].includes(t)) return 'text-rose-400 bg-rose-500/10 border-rose-500/20';
  if (['pptx', 'ppt'].includes(t)) return 'text-orange-400 bg-orange-500/10 border-orange-500/20';
  if (['docx', 'doc'].includes(t)) return 'text-blue-400 bg-blue-500/10 border-blue-500/20';
  if (['xlsx', 'xls', 'csv'].includes(t)) return 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20';
  if (['png', 'jpg', 'jpeg'].includes(t)) return 'text-fuchsia-400 bg-fuchsia-500/10 border-fuchsia-500/20';
  return 'text-violet-400 bg-violet-500/10 border-violet-500/20';
};

const getSmallFileIconBg = (type: string) => {
  const t = type.toLowerCase();
  if (['pdf'].includes(t)) return 'bg-rose-500/10 border-rose-500/20';
  if (['pptx', 'ppt'].includes(t)) return 'bg-orange-500/10 border-orange-500/20';
  if (['docx', 'doc'].includes(t)) return 'bg-blue-500/10 border-blue-500/20';
  if (['xlsx', 'xls', 'csv'].includes(t)) return 'bg-emerald-500/10 border-emerald-500/20';
  return 'bg-violet-500/10 border-violet-500/20';
};

export default function KnowledgePage() {
  const { tier } = useBillingStore();
  const [kbs, setKbs] = useState<any[]>([]);
  const [view, setView] = useState<'grid' | 'detail'>('grid');
  const [activeKb, setActiveKb] = useState<any | null>(null);
  const [activeDoc, setActiveDoc] = useState<any | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isUploading, setIsUploading] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  
  // Create Modal
  const [showCreate, setShowCreate] = useState(false);
  const [newKbName, setNewKbName] = useState("");
  const [newKbDesc, setNewKbDesc] = useState("");

  // Delete Document Modal
  const [docToDelete, setDocToDelete] = useState<any | null>(null);
  
  // Delete KB Modal
  const [kbToDelete, setKbToDelete] = useState<any | null>(null);

  // Add Source Modal
  const [showAddSource, setShowAddSource] = useState(false);
  const [sourceTab, setSourceTab] = useState<'files'|'folder'|'github'>('files');
  const [githubRepos, setGithubRepos] = useState<any[]>([]);
  const [isLoadingRepos, setIsLoadingRepos] = useState(false);
  const [uploadStats, setUploadStats] = useState({ current: 0, total: 0, filename: '' });

  const fetchKBs = async (background = false) => {
    if (!background) setIsLoading(true);
    try {
      const res = await fetch('/api/knowledge/list');
      const data = await res.json();
      setKbs(data.kbs || []);
      
      // Update activeKb using the functional updater to avoid stale closure issues during polling
      setActiveKb((prevKb: any) => {
        if (!prevKb) return null;
        const updatedActive = (data.kbs || []).find((k: any) => k.id === prevKb.id);
        return updatedActive || prevKb;
      });
    } catch (e: any) {
      console.error("Failed to fetch KBs:", e.message || e);
    }
    if (!background) setIsLoading(false);
  };

  useEffect(() => {
    fetchKBs();
    // Poll the API every 5 seconds silently in the background
    // This ensures background Inngest jobs (like document processing) automatically appear in the UI without a manual refresh!
    const interval = setInterval(() => fetchKBs(true), 5000);
    return () => clearInterval(interval);
  }, []);

  const handleCreate = async () => {
    if (!newKbName) return;
    
    if (tier === 'free' && kbs.length >= 1) {
      alert("Free tier is limited to 1 Knowledge Base. Please upgrade to Pro in the Billing Studio.");
      return;
    }

    try {
      const res = await fetch('/api/knowledge/create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: newKbName, description: newKbDesc })
      });
      const data = await res.json();
      if (!res.ok) {
        alert(data.error || "Failed to create Knowledge Base");
        return;
      }
      setNewKbName("");
      setNewKbDesc("");
      setShowCreate(false);
      fetchKBs();
    } catch (e: any) {
      console.error("Failed to create KB:", e.message || e);
    }
  };

  const handleUpload = async (e: any) => {
    // Legacy single file upload, replaced by handleMultiUpload below, but keeping for safety if needed
    const file = e.target.files[0];
    if (!file || !activeKb) return;

    setIsUploading(true);
    const formData = new FormData();
    formData.append("file", file);
    formData.append("kbId", activeKb.id.toString());

    try {
      const res = await fetch('/api/knowledge/upload', {
        method: 'POST',
        body: formData
      });
      if (res.ok) {
        fetchKBs();
      } else {
        const errData = await res.json();
        alert(errData.error || "Failed to process file.");
      }
    } catch (err: any) {
      console.error("Error uploading file:", err.message || err);
      alert("Error uploading file.");
    }
    setIsUploading(false);
  };

  const handleMultiUpload = async (e: any) => {
    const files = Array.from(e.target.files) as File[];
    if (!files.length || !activeKb) return;

    // Basic client-side filtering for massive junk folders
    const allowedFiles = files.filter(f => {
      const path = f.webkitRelativePath || f.name;
      if (path.includes('node_modules/') || path.includes('.git/') || path.includes('.next/') || path.includes('dist/') || path.includes('build/')) {
        return false;
      }
      return true;
    });

    if (allowedFiles.length === 0) {
      // We will just use a simple error state, but avoiding system alerts if possible. 
      // For simple errors before upload starts, alert is okay, but let's keep it clean.
      alert("No valid files found to upload.");
      return;
    }

    let finalFiles = allowedFiles;
    const MAX_FILES = 250;
    if (finalFiles.length > MAX_FILES) {
      finalFiles.sort((a, b) => getFilePriorityScore(b.name) - getFilePriorityScore(a.name));
      finalFiles = finalFiles.slice(0, MAX_FILES);
      alert(`You selected ${allowedFiles.length} valid files, but the free tier is capped at ${MAX_FILES} files per upload. We have automatically selected the ${MAX_FILES} most important source files to upload.`);
    }

    setIsUploading(true);
    setUploadStats({ current: 0, total: finalFiles.length, filename: '' });
    
    let successCount = 0;
    
    for (let i = 0; i < finalFiles.length; i++) {
      const file = finalFiles[i];
      if (!file) continue;
      if (file.size > 25 * 1024 * 1024) {
        console.warn(`Skipping ${file.name} - file too large (>25MB)`);
        continue;
      }
      setUploadStats({ current: i + 1, total: allowedFiles.length, filename: file.webkitRelativePath || file.name });
      
      const formData = new FormData();
      formData.append("file", file);
      formData.append("kbId", activeKb.id.toString());
      
      if (file.webkitRelativePath) {
         formData.append("filePath", file.webkitRelativePath);
      }

      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 60000); // 60s timeout per file
      
      try {
        const res = await fetch('/api/knowledge/upload?skipEnhance=true', {
          method: 'POST',
          body: formData,
          signal: controller.signal
        });
        if (res.ok) {
          successCount++;
        } else {
          const errData = await res.json();
          if (errData.error && errData.error.toLowerCase().includes('limit')) {
            alert(errData.error);
            break; // Stop trying to upload more files if we hit a limit
          }
          console.error(`Failed to upload ${file.name}:`, errData.error);
        }
      } catch (err: any) {
        if (err.name === 'AbortError') {
          console.warn(`Upload timed out (60s) for ${file.name}`);
        } else {
          console.error(`Failed to upload ${file.name}:`, err.message || err);
        }
      } finally {
        clearTimeout(timeoutId);
      }
    }

    fetchKBs();
    setIsUploading(false);
    setUploadStats({ current: 0, total: 0, filename: '' });
    setShowAddSource(false);
  };

  const handleNativeFolderUpload = async () => {
    if (!activeKb) return;
    try {
      // @ts-ignore - TS doesn't know about showDirectoryPicker
      const dirHandle = await window.showDirectoryPicker();
      
      setIsUploading(true);

      const ig = ignore().add(UNIVERSAL_IGNORES);

      // Try to find .gitignore in the root
      try {
        const gitignoreHandle = await dirHandle.getFileHandle('.gitignore');
        const file = await gitignoreHandle.getFile();
        const text = await file.text();
        ig.add(text);
      } catch (e) {
        // No .gitignore found, totally fine
      }

      const filesToUpload: { file: File, entryPath: string }[] = [];

      async function scanDirectory(handle: any, currentPath: string) {
        for await (const entry of handle.values()) {
          const entryPath = currentPath ? `${currentPath}/${entry.name}` : entry.name;
          
          // Check if this path is ignored
          // We append a trailing slash for directories so ignore library matches properly if the user used `folder/`
          const isDir = entry.kind === 'directory';
          const testPath = isDir ? `${entryPath}/` : entryPath;
          
          if (ig.ignores(testPath)) {
            continue;
          }

          if (isDir) {
            await scanDirectory(entry, entryPath);
          } else if (entry.kind === 'file') {
            const file = await entry.getFile();
            filesToUpload.push({ file, entryPath });
          }
        }
      }

      await scanDirectory(dirHandle, '');

      if (filesToUpload.length === 0) {
        alert("No valid files found to upload.");
        setIsUploading(false);
        return;
      }

      let finalFiles = filesToUpload;
      const MAX_FILES = 250;
      if (finalFiles.length > MAX_FILES) {
        finalFiles.sort((a, b) => getFilePriorityScore(b.file.name) - getFilePriorityScore(a.file.name));
        finalFiles = finalFiles.slice(0, MAX_FILES);
        alert(`Your folder contains ${filesToUpload.length} valid files, but the free tier is capped at ${MAX_FILES} files. We have automatically selected the ${MAX_FILES} most important source files to upload.`);
      }

      setIsUploading(true);
      setUploadStats({ current: 0, total: finalFiles.length, filename: '' });

      let successCount = 0;
      
      for (let i = 0; i < finalFiles.length; i++) {
        const item = finalFiles[i];
        if (!item || !item.file) continue;
        if (item.file.size > 25 * 1024 * 1024) {
          console.warn(`Skipping ${item.file.name} - file too large (>25MB)`);
          continue;
        }
        setUploadStats({ current: i + 1, total: filesToUpload.length, filename: item.entryPath });

        const formData = new FormData();
        formData.append("file", item.file);
        formData.append("kbId", activeKb.id.toString());
        formData.append("filePath", item.entryPath);

        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 60000); // 60s timeout per file

        try {
          const res = await fetch('/api/knowledge/upload?skipEnhance=true', {
            method: 'POST',
            body: formData,
            signal: controller.signal
          });
          if (res.ok) successCount++;
        } catch (err: any) {
          if (err.name === 'AbortError') {
            console.warn(`Upload timed out (60s) for ${item.file.name}`);
          } else {
            console.error(`Failed to upload ${item.file.name}:`, err.message || err);
          }
        } finally {
          clearTimeout(timeoutId);
        }
      }

      fetchKBs();
      setIsUploading(false);
      setUploadStats({ current: 0, total: 0, filename: '' });
      setShowAddSource(false);

    } catch (err: any) {
      if (err.name !== 'AbortError') {
        console.error("Failed to read folder:", err.message || err);
        alert("Failed to read folder. " + err.message);
      }
      setIsUploading(false);
    }
  };

  const fetchGithubRepos = async () => {
    setIsLoadingRepos(true);
    try {
      const res = await fetch('/api/knowledge/sources/github/installations');
      const data = await res.json();
      if (data.success) {
        setGithubRepos(data.repositories);
      } else {
         console.warn(data.error);
      }
    } catch (e) {
      console.error(e);
    }
    setIsLoadingRepos(false);
  };

  const handleConnectGithub = async (repo: any) => {
    setIsUploading(true);
    try {
      const res = await fetch('/api/knowledge/sources/github/create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ kbId: activeKb.id, repo })
      });
      if (res.ok) {
        setShowAddSource(false);
        fetchKBs();
        alert("GitHub Repository connected and sync job queued!");
      } else {
        alert("Failed to connect GitHub Repository.");
      }
    } catch (e) {
      console.error(e);
      alert("Error connecting GitHub.");
    }
    setIsUploading(false);
  };

  const handleDeleteDocument = async () => {
    if (!docToDelete) return;
    const docId = docToDelete.id;
    
    try {
      const res = await fetch('/api/knowledge/delete-document', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: docId })
      });
      if (res.ok) {
        if (activeDoc?.id === docId) setActiveDoc(null);
        fetchKBs();
      } else {
        alert("Failed to delete document.");
      }
    } catch (e) {
      console.error(e);
      alert("Error deleting document.");
    }
    setDocToDelete(null);
  };

  const handleDeleteKb = async () => {
    if (!kbToDelete) return;
    const id = kbToDelete.id;
    
    try {
      const res = await fetch('/api/knowledge/delete', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id })
      });
      if (res.ok) {
        if (activeKb?.id === id) {
          setActiveKb(null);
          setView('grid');
        }
        fetchKBs();
      } else {
        alert("Failed to delete Knowledge Base.");
      }
    } catch (e) {
      console.error(e);
      alert("Error deleting Knowledge Base.");
    }
    setKbToDelete(null);
  };

  const openDetail = (kb: any) => {
    setActiveKb(kb);
    setActiveDoc(null);
    setView('detail');
  };

  const filteredKbs = kbs.filter(kb => kb.name.toLowerCase().includes(searchQuery.toLowerCase()));
  const totalFiles = kbs.reduce((acc, kb) => acc + (kb.documentCount || 0), 0);

  return (
    <div className="flex-1 flex flex-col overflow-hidden bg-[#0a0a0c] text-white">
      
      {view === 'grid' && (
        <div className="flex-1 overflow-y-auto custom-scrollbar">
          <div className="p-8 max-w-7xl mx-auto w-full">
          {/* Header */}
          <div className="flex justify-between items-start mb-8">
            <div>
              <h1 className="text-3xl font-bold text-white tracking-tight mb-1">Knowledge Bases</h1>
              <p className="text-zinc-400 text-sm">{kbs.length} bases · {totalFiles} files indexed</p>
            </div>
            <button 
              onClick={() => setShowCreate(true)}
              className="bg-[#c026d3] hover:bg-[#a21caf] text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-2 shadow-[0_0_20px_rgba(192,38,211,0.3)]"
            >
              <Plus className="w-4 h-4" /> New Knowledge Base
            </button>
          </div>

          {/* Search */}
          <div className="relative mb-8 max-w-md">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-500" />
            <input 
              type="text" 
              placeholder="Search knowledge bases..." 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-zinc-900/50 border border-zinc-800 rounded-xl pl-10 pr-4 py-2.5 text-sm text-zinc-200 focus:outline-none focus:border-zinc-700 transition-colors"
            />
          </div>

          {/* Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {isLoading ? (
               Array.from({ length: 3 }).map((_, i) => (
                  <div key={`skeleton-${i}`} className="bg-[#121217] border border-white/5 rounded-2xl p-6 h-[220px] animate-pulse flex flex-col">
                     <div className="flex justify-between items-start mb-4">
                        <div className="w-12 h-12 bg-white/5 rounded-xl"></div>
                        <div className="w-12 h-6 bg-white/5 rounded-full"></div>
                     </div>
                     <div className="w-3/4 h-6 bg-white/10 rounded mb-3"></div>
                     <div className="w-full h-4 bg-white/5 rounded mb-2"></div>
                     <div className="w-2/3 h-4 bg-white/5 rounded mb-auto"></div>
                     <div className="flex gap-2 pt-4 border-t border-white/5 mt-4">
                        <div className="w-7 h-7 rounded-md bg-white/5"></div>
                        <div className="w-7 h-7 rounded-md bg-white/5"></div>
                     </div>
                  </div>
               ))
            ) : (
               <>
                 {/* Add New Card */}
                 <div 
                   onClick={() => setShowCreate(true)}
                   className="border border-dashed border-white/10 hover:border-white/20 rounded-2xl p-6 cursor-pointer flex flex-col items-center justify-center min-h-[220px] transition-colors group bg-black/20"
                 >
                   <div className="w-10 h-10 rounded-full border border-white/10 flex items-center justify-center mb-4 group-hover:bg-white/5 transition-colors">
                     <Plus className="w-5 h-5 text-zinc-400 group-hover:text-white" />
                   </div>
                   <h3 className="font-medium text-zinc-300 group-hover:text-white mb-1">Add Knowledge Base</h3>
                   <p className="text-xs text-zinc-500 text-center">Upload docs, PDFs, sheets & more</p>
                 </div>

                 {filteredKbs.map(kb => {
                   const uniqueTypes = Array.from(new Set((kb.documents || []).map((d: any) => d.sourceType)));
                   const displayTypes = uniqueTypes.slice(0, 4);
                   const extraTypes = uniqueTypes.length > 4 ? uniqueTypes.length - 4 : 0;

                   return (
                     <div 
                       key={kb.id} 
                       onClick={() => openDetail(kb)}
                       className="bg-[#121217] border border-white/5 hover:border-white/10 rounded-2xl p-6 cursor-pointer group transition-all hover:bg-[#16161c]"
                     >
                       <div className="flex justify-between items-start mb-4">
                         <div className={`w-12 h-12 rounded-xl flex items-center justify-center shadow-lg ${getKbColors(kb.color || 'fuchsia')}`}>
                           <Database className="w-6 h-6" />
                         </div>
                         <div className="flex flex-col items-end gap-2">
                           <button 
                             onClick={(e) => { e.stopPropagation(); setKbToDelete(kb); }}
                             className="text-zinc-500 hover:text-red-400 p-1 opacity-0 group-hover:opacity-100 transition-all rounded hover:bg-white/5"
                             title="Delete Knowledge Base"
                           >
                             <Trash2 className="w-4 h-4" />
                           </button>
                           {kb.activeJobsCount > 0 ? (
                             <span className="bg-fuchsia-500/10 border border-fuchsia-500/20 text-fuchsia-400 text-[10px] font-medium px-2.5 py-1 rounded-full flex items-center gap-1.5">
                               <RefreshCw className="w-3 h-3 animate-spin" />
                               Processing {kb.activeJobsCount}
                             </span>
                           ) : (
                             <span className="bg-white/5 border border-white/10 text-zinc-300 text-[10px] font-medium px-2.5 py-1 rounded-full">
                               {kb.documentCount || 0} files
                             </span>
                           )}
                         </div>
                       </div>
                       
                       <h3 className="text-lg font-semibold text-white mb-2 group-hover:text-fuchsia-400 transition-colors">{kb.name}</h3>
                       <p className="text-sm text-zinc-400 mb-6 line-clamp-2 h-10">{kb.description || 'No description provided.'}</p>
                       
                       <div className="flex items-center gap-2 pt-4 border-t border-white/5">
                         {displayTypes.length > 0 ? displayTypes.map((type: any, idx) => (
                           <div key={idx} className={`w-7 h-7 rounded-md flex items-center justify-center border ${getSmallFileIconBg(type)}`}>
                             {getFileIcon(type)}
                           </div>
                         )) : (
                           <span className="text-xs text-zinc-600">Empty</span>
                         )}
                         {extraTypes > 0 && (
                           <span className="text-xs text-zinc-500 font-medium ml-1">+{extraTypes}</span>
                         )}
                       </div>
                     </div>
                   );
                 })}
               </>
            )}
          </div>
        </div>
      </div>
      )}

      {view === 'detail' && activeKb && (
        <div className="flex-1 flex flex-col overflow-hidden">
          {/* Detail Header */}
          <div className="border-b border-white/5 bg-[#0a0a0c] p-6 z-10 flex-shrink-0">
            <div className="max-w-[1400px] mx-auto flex items-center justify-between">
              <div className="flex items-center gap-4">
                <button 
                  onClick={() => setView('grid')}
                  className="w-8 h-8 rounded-full bg-white/5 hover:bg-white/10 flex items-center justify-center transition-colors border border-white/5"
                >
                  <ArrowLeft className="w-4 h-4 text-zinc-400" />
                </button>
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center shadow-lg ${getKbColors(activeKb.color || 'fuchsia')}`}>
                  <Database className="w-5 h-5" />
                </div>
                <div>
                  <h1 className="text-xl font-bold text-white">{activeKb.name}</h1>
                  <p className="text-xs text-zinc-400">{activeKb.description || 'No description provided.'}</p>
                </div>
              </div>

              <div className="flex items-center gap-3">
                {isUploading && (
                   <span className="text-xs text-zinc-400 flex items-center gap-2">
                     <RefreshCw className="w-3 h-3 animate-spin" /> Processing Source...
                   </span>
                )}
                <Link 
                  href={`/knowledge-base/${activeKb.id}/architecture`}
                  className="flex items-center gap-2 bg-gradient-to-r from-violet-600 to-fuchsia-600 hover:opacity-90 text-white px-4 py-2 rounded-lg text-sm font-medium transition-opacity shadow-[0_0_15px_rgba(139,92,246,0.3)]"
                >
                  <Network className="w-4 h-4" />
                  View Node Tree
                </Link>
                <button 
                  onClick={() => { setShowAddSource(true); if(githubRepos.length === 0) fetchGithubRepos(); }}
                  disabled={isUploading}
                  className={`flex items-center gap-2 bg-zinc-900 border border-white/10 hover:bg-zinc-800 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors ${isUploading ? 'opacity-50' : ''}`}
                >
                  <Plus className="w-4 h-4" />
                  Add Source
                </button>
              </div>
            </div>
          </div>

          <PanelGroup direction="horizontal" className="flex-1 overflow-hidden">
            <Panel defaultSize={activeDoc ? 60 : 100} minSize={30} className="flex flex-col overflow-hidden h-full">
              <div className="flex-1 overflow-y-auto custom-scrollbar p-6">
                <div className="max-w-[1400px] mx-auto w-full">
                  <div className="bg-[#121217] border border-white/5 rounded-2xl overflow-hidden">
                  <div className="grid grid-cols-12 gap-4 px-6 py-4 border-b border-white/5 text-[11px] font-semibold text-zinc-500 uppercase tracking-wider bg-[#0f0f13]">
                    <div className="col-span-6">Name</div>
                    <div className="col-span-2">Type</div>
                    <div className="col-span-3">Updated</div>
                    <div className="col-span-1 text-right">Actions</div>
                  </div>
                  
                  <div className="divide-y divide-white/5">
                    {activeKb.activeJobsCount > 0 && (
                      <div className="px-6 py-4 bg-fuchsia-500/5 flex items-center justify-center gap-3 border-b border-fuchsia-500/10">
                        <RefreshCw className="w-4 h-4 animate-spin text-fuchsia-400" />
                        <span className="text-sm text-fuchsia-200 font-medium">Processing background tasks... New documents will appear here when ready.</span>
                      </div>
                    )}
                    {activeKb.documents?.length > 0 ? (
                      activeKb.documents.map((doc: any) => {
                        const badgeColors = getFileBadgeColors(doc.sourceType);
                        const iconBg = getSmallFileIconBg(doc.sourceType);
                        const isActive = activeDoc?.id === doc.id;
                        return (
                          <div 
                            key={doc.id} 
                            onClick={() => setActiveDoc(doc)}
                            className={`grid grid-cols-12 gap-4 px-6 py-4 items-center cursor-pointer transition-colors ${isActive ? 'bg-fuchsia-500/10 border-l-2 border-fuchsia-500 pl-4' : 'hover:bg-white/[0.02] border-l-2 border-transparent'}`}
                          >
                            <div className="col-span-6 flex items-center gap-4">
                              <div className={`w-9 h-9 rounded-lg flex items-center justify-center border ${iconBg}`}>
                                {getFileIcon(doc.sourceType)}
                              </div>
                              <div>
                                <p className={`text-sm font-medium truncate ${isActive ? 'text-fuchsia-300' : 'text-zinc-200'}`}>{doc.title}</p>
                                <p className="text-[11px] text-zinc-500 mt-0.5">{formatBytes(doc.sizeBytes || 0)}</p>
                              </div>
                            </div>
                            <div className="col-span-2">
                              <span className={`text-[10px] font-bold px-2 py-0.5 rounded uppercase border ${badgeColors}`}>
                                {doc.sourceType}
                              </span>
                            </div>
                            <div className="col-span-3 text-xs text-zinc-400">
                              {formatTimeAgo(doc.updatedAt || doc.createdAt)}
                            </div>
                            <div className="col-span-1 text-right">
                              <button 
                                onClick={(e) => { e.stopPropagation(); setDocToDelete(doc); }}
                                className="text-zinc-500 hover:text-red-400 transition-colors p-1 rounded hover:bg-white/5"
                              >
                                <Trash2 className="w-4 h-4" />
                              </button>
                            </div>
                          </div>
                        );
                      })
                    ) : (
                      <div className="p-12 text-center flex flex-col items-center justify-center">
                        <Database className="w-8 h-8 text-zinc-600 mb-4" />
                        <p className="text-sm text-zinc-400 mb-1">No files in this Knowledge Base yet.</p>
                        <p className="text-xs text-zinc-600">Upload a document to get started.</p>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>
          </Panel>

            {activeDoc && (
              <>
                <PanelResizeHandle className="w-1 bg-white/5 hover:bg-fuchsia-500/50 transition-colors cursor-col-resize active:bg-fuchsia-500" />
                <Panel defaultSize={40} minSize={20} className="bg-[#0f0f13] border-l border-white/5 flex flex-col overflow-hidden h-full">
                  <div className="p-4 border-b border-white/5 flex justify-between items-center sticky top-0 bg-[#0f0f13] z-10 shadow-sm flex-shrink-0">
                    <h3 className="font-bold text-white flex items-center gap-3 truncate pr-4">
                      <div className={`p-1.5 rounded-md ${getSmallFileIconBg(activeDoc.sourceType)}`}>
                        {getFileIcon(activeDoc.sourceType)}
                      </div>
                      <span className="truncate">{activeDoc.title}</span>
                    </h3>
                    <button 
                      onClick={() => setActiveDoc(null)} 
                      className="p-1.5 hover:bg-white/10 rounded-md transition-colors text-zinc-400 hover:text-white flex-shrink-0"
                    >
                      <X className="w-4 h-4" />
                    </button>
                  </div>
                  <div className="p-6 overflow-y-auto flex-1 min-h-0 custom-scrollbar">
                    <div className="prose prose-invert prose-sm max-w-none text-zinc-300">
                      <ReactMarkdown>
                        {activeDoc.enhancedContent || activeDoc.content || 'No text content available for this document.'}
                      </ReactMarkdown>
                    </div>
                  </div>
                </Panel>
              </>
            )}
          </PanelGroup>
        </div>
      )}

      {/* Create Modal */}
      {showCreate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
          <div className="bg-[#121217] p-6 rounded-2xl shadow-2xl max-w-md w-full border border-white/10">
            <h3 className="text-lg font-bold text-white mb-1">Create Knowledge Base</h3>
            <p className="text-xs text-zinc-400 mb-5">Organize your files for AI generation.</p>
            
            <div className="space-y-4 mb-6">
              <div>
                <label className="block text-xs font-medium text-zinc-400 mb-1.5 uppercase tracking-wide">Name</label>
                <input 
                  type="text"
                  placeholder="e.g. Q3 Marketing Reports"
                  value={newKbName}
                  onChange={(e) => setNewKbName(e.target.value)}
                  className="w-full bg-black/40 border border-white/10 rounded-lg px-3 py-2 text-sm text-zinc-200 focus:ring-1 focus:ring-fuchsia-500 outline-none"
                />
              </div>
              <div>
                <label className="block text-xs font-medium text-zinc-400 mb-1.5 uppercase tracking-wide">Description</label>
                <textarea 
                  placeholder="What is this knowledge base for?"
                  value={newKbDesc}
                  onChange={(e) => setNewKbDesc(e.target.value)}
                  className="w-full bg-black/40 border border-white/10 rounded-lg px-3 py-2 text-sm text-zinc-200 focus:ring-1 focus:ring-fuchsia-500 outline-none resize-none h-20"
                />
              </div>
            </div>

            <div className="flex justify-end gap-3 border-t border-white/5 pt-4">
              <button 
                onClick={() => setShowCreate(false)}
                className="px-4 py-2 text-sm font-medium text-zinc-400 hover:text-white transition-colors"
              >
                Cancel
              </button>
              <button 
                onClick={handleCreate}
                disabled={!newKbName}
                className="bg-fuchsia-600 hover:bg-fuchsia-500 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
              >
                Create
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {docToDelete && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
          <div className="bg-[#121217] p-6 rounded-2xl shadow-2xl max-w-sm w-full border border-white/10">
            <h3 className="text-lg font-bold text-white mb-2">Delete Document?</h3>
            <p className="text-sm text-zinc-400 mb-6">
              Are you sure you want to delete <span className="text-white font-medium">"{docToDelete.title}"</span>? This action cannot be undone.
            </p>
            
            <div className="flex justify-end gap-3 border-t border-white/5 pt-4">
              <button 
                onClick={() => setDocToDelete(null)}
                className="px-4 py-2 text-sm font-medium text-zinc-400 hover:text-white transition-colors"
              >
                Cancel
              </button>
              <button 
                onClick={handleDeleteDocument}
                className="bg-red-500/20 hover:bg-red-500/30 text-red-400 border border-red-500/30 px-4 py-2 rounded-lg text-sm font-medium transition-colors"
              >
                Delete
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Delete KB Confirmation Modal */}
      {kbToDelete && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
          <div className="bg-[#121217] p-6 rounded-2xl shadow-2xl max-w-sm w-full border border-white/10">
            <h3 className="text-lg font-bold text-white mb-2">Delete Knowledge Base?</h3>
            <p className="text-sm text-zinc-400 mb-6">
              Are you sure you want to delete <span className="text-white font-medium">"{kbToDelete.name}"</span>? This will permanently delete all associated documents, chats, and sources. This action cannot be undone.
            </p>
            
            <div className="flex justify-end gap-3 border-t border-white/5 pt-4">
              <button 
                onClick={() => setKbToDelete(null)}
                className="px-4 py-2 text-sm font-medium text-zinc-400 hover:text-white transition-colors"
              >
                Cancel
              </button>
              <button 
                onClick={handleDeleteKb}
                className="bg-red-500/20 hover:bg-red-500/30 text-red-400 border border-red-500/30 px-4 py-2 rounded-lg text-sm font-medium transition-colors"
              >
                Delete Knowledge Base
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Add Source Modal */}
      {showAddSource && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
          <div className="bg-[#121217] p-6 rounded-2xl shadow-2xl max-w-lg w-full border border-white/10 flex flex-col h-[500px]">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-lg font-bold text-white">Add Knowledge Source</h3>
              <button onClick={() => setShowAddSource(false)} className="text-zinc-500 hover:text-white transition-colors">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="flex gap-2 mb-6 bg-black/40 p-1 rounded-lg shrink-0">
              <button 
                onClick={() => setSourceTab('files')}
                className={`flex-1 py-1.5 text-xs font-medium rounded-md transition-colors flex items-center justify-center gap-2 ${sourceTab === 'files' ? 'bg-zinc-800 text-white' : 'text-zinc-400 hover:text-white'}`}
              >
                <FileText className="w-3.5 h-3.5" /> Files
              </button>
              <button 
                onClick={() => setSourceTab('folder')}
                className={`flex-1 py-1.5 text-xs font-medium rounded-md transition-colors flex items-center justify-center gap-2 ${sourceTab === 'folder' ? 'bg-zinc-800 text-white' : 'text-zinc-400 hover:text-white'}`}
              >
                <FolderUp className="w-3.5 h-3.5" /> Folder
              </button>
              <button 
                onClick={() => { setSourceTab('github'); fetchGithubRepos(); }}
                className={`flex-1 py-1.5 text-xs font-medium rounded-md transition-colors flex items-center justify-center gap-2 ${sourceTab === 'github' ? 'bg-zinc-800 text-white' : 'text-zinc-400 hover:text-white'}`}
              >
                <GitBranch className="w-3.5 h-3.5" /> GitHub App
              </button>
            </div>

            <div className="flex-1 overflow-y-auto custom-scrollbar pr-2">
              {isUploading ? (
                <div className="flex flex-col items-center justify-center h-full px-6">
                  <div className="w-16 h-16 bg-blue-500/10 rounded-full flex items-center justify-center mb-6">
                    <RefreshCw className="w-8 h-8 text-blue-400 animate-spin" />
                  </div>
                  <h3 className="text-xl font-bold text-white mb-2">
                    {uploadStats.total > 0 ? 'Syncing Knowledge' : 'Scanning Files...'}
                  </h3>
                  
                  {uploadStats.total > 0 ? (
                    <>
                      <p className="text-sm text-zinc-400 mb-8 text-center w-full truncate px-4" title={uploadStats.filename}>
                        {uploadStats.filename || 'Preparing files...'}
                      </p>
                      
                      <div className="w-full bg-zinc-800 rounded-full h-2.5 mb-3 overflow-hidden border border-white/5">
                        <div 
                          className="bg-blue-500 h-2.5 rounded-full transition-all duration-300 ease-out" 
                          style={{ width: `${Math.max(5, (uploadStats.current / uploadStats.total) * 100)}%` }}
                        ></div>
                      </div>
                      
                      <div className="flex justify-between w-full text-xs text-zinc-400 font-medium">
                        <span>{Math.round((uploadStats.current / uploadStats.total) * 100)}%</span>
                        <span>{uploadStats.current} / {uploadStats.total} files</span>
                      </div>
                    </>
                  ) : (
                    <p className="text-sm text-zinc-400 mb-8 text-center w-full px-4">
                      Parsing directory structure and filtering ignored files...
                    </p>
                  )}
                </div>
              ) : (
                <>
                  {sourceTab === 'files' && (
                    <div className="border-2 border-dashed border-white/10 hover:border-white/20 rounded-xl p-8 flex flex-col items-center justify-center h-full transition-colors relative">
                      <input 
                        type="file" 
                        multiple
                        onChange={handleMultiUpload}
                        className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                      />
                      <UploadCloud className="w-10 h-10 text-zinc-500 mb-3" />
                      <p className="text-sm text-white font-medium mb-1">Click or drag files here</p>
                      <p className="text-xs text-zinc-500 text-center">Upload multiple PDFs, documents, or media files.</p>
                    </div>
                  )}

                  {sourceTab === 'folder' && (
                    <div className="border-2 border-dashed border-white/10 hover:border-white/20 rounded-xl p-8 flex flex-col items-center justify-center h-full transition-colors relative">
                      <button 
                        onClick={handleNativeFolderUpload}
                        className="absolute inset-0 w-full h-full cursor-pointer z-10"
                        aria-label="Select Folder"
                      />
                      <FolderUp className="w-10 h-10 text-zinc-500 mb-3" />
                      <p className="text-sm text-white font-medium mb-1">Select a Local Folder</p>
                      <p className="text-xs text-zinc-500 text-center px-4 max-w-[300px]">
                        Powered by your OS. Automatically skips <code className="bg-zinc-800 px-1 rounded text-zinc-300">node_modules</code>, <code className="bg-zinc-800 px-1 rounded text-zinc-300">build</code>, and completely respects your <code className="bg-zinc-800 px-1 rounded text-zinc-300">.gitignore</code> file for maximum performance!
                      </p>
                      <div className="mt-4 bg-zinc-800 text-xs px-4 py-1.5 rounded-full text-zinc-300 font-medium z-0">
                        Browse Files
                      </div>
                    </div>
                  )}

                  {sourceTab === 'github' && (
                    <div className="h-full flex flex-col">
                      {isLoadingRepos ? (
                        <div className="flex flex-col items-center justify-center h-full">
                          <RefreshCw className="w-6 h-6 text-zinc-500 animate-spin mb-3" />
                          <p className="text-sm text-zinc-400">Loading your GitHub App installations...</p>
                        </div>
                      ) : githubRepos.length > 0 ? (
                        <div className="space-y-2 pb-4">
                          {githubRepos.map(repo => (
                            <div key={repo.id} className="flex items-center justify-between p-3 rounded-lg border border-white/5 bg-white/[0.02] hover:bg-white/[0.05] transition-colors">
                              <div className="flex items-center gap-3 overflow-hidden">
                                <img src={repo.ownerAvatarUrl} alt={repo.ownerLogin} className="w-8 h-8 rounded-full border border-white/10 shrink-0" />
                                <div className="truncate">
                                  <p className="text-sm font-medium text-white truncate">{repo.fullName}</p>
                                  <div className="flex items-center gap-2 mt-0.5">
                                    <span className="text-[10px] text-zinc-500 border border-zinc-800 rounded px-1">{repo.private ? 'Private' : 'Public'}</span>
                                    <span className="text-[10px] text-zinc-500">Branch: {repo.defaultBranch}</span>
                                  </div>
                                </div>
                              </div>
                              <button 
                                onClick={() => handleConnectGithub(repo)}
                                className="text-xs bg-zinc-800 hover:bg-zinc-700 text-white px-3 py-1.5 rounded-md transition-colors whitespace-nowrap shrink-0 ml-3"
                              >
                                Connect
                              </button>
                            </div>
                          ))}
                        </div>
                      ) : (
                        <div className="flex flex-col items-center justify-center h-full text-center">
                          <GitBranch className="w-10 h-10 text-zinc-600 mb-3" />
                          <p className="text-sm text-zinc-300 mb-2">No repositories found.</p>
                          <p className="text-xs text-zinc-500 mb-4 px-4">Install your GenWorkAI GitHub App on your repositories to see them here.</p>
                          <a href={`https://github.com/apps/genworkai/installations/new`} target="_blank" rel="noreferrer" className="text-xs text-blue-400 hover:underline">
                            Manage GitHub App Installations ↗
                          </a>
                        </div>
                      )}
                    </div>
                  )}
                </>
              )}
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
