import { NextResponse } from 'next/server';
import AdmZip from 'adm-zip';
import { db } from '../../../../../db';
import { documents, documentChunks, knowledgeSources, syncJobs } from '../../../../../db/schema';
import { generateEmbedding } from '../../../../../lib/embeddings';
import { extractTextFromBuffer, cleanExtractedText, enhanceTextWithAI, smartChunkMarkdown, extractRelationships } from '../../../../../lib/knowledge-pipeline';
import { requireUser, requireOwnership } from '../../../../../lib/auth';
import { RateLimitService } from '../../../../../lib/security/rate-limit';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

export async function OPTIONS() {
  return NextResponse.json({}, { headers: corsHeaders });
}

function isProcessableFile(filename: string): boolean {
  const ignored = [
    // Version Control & IDE
    '.git/', '.svn/', '.hg/', '.idea/', '.vscode/', '.DS_Store',
    
    // Build folders & Caches
    'node_modules/', 'dist/', 'build/', '.next/', 'out/', '.nuxt/', '.cache/', 
    '.gradle/', '.dart_tool/', 'venv/', '__pycache__/', '.pytest_cache/', 
    'Pods/', 'target/', 'bin/', 'obj/', 'DerivedData/', 'coverage/', '.expo/',

    // Lock files
    'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'bun.lockb',
    'Cargo.lock', 'Gemfile.lock', 'composer.lock', 'pubspec.lock', 'Podfile.lock', 'mix.lock',
    
    // Autogenerated Code & Maps
    '.g.dart', '.freezed.dart', '.mocks.dart', '.pb.go', '.pb.cc', '.designer.cs',
    '.min.js', '.min.css', '.map',

    // Media & Binaries
    '.png', '.jpg', '.jpeg', '.gif', '.ico', '.svg', '.webp',
    '.woff', '.woff2', '.ttf', '.eot',
    '.mp4', '.mov', '.webm', '.mp3', '.wav',
    '.riv', '.lottie', '.zip', '.tar', '.gz', '.rar', '.7z',
    '.exe', '.dll', '.so', '.dylib', '.bin', '.iso'
  ];
  return !ignored.some(i => filename.includes(i));
}

export async function POST(req: Request) {
  try {
    const { user, error: authError } = await requireUser();
    if (authError) return authError;

    const rateLimitResponse = await RateLimitService.check(user.id, 'upload');
    if (rateLimitResponse) return rateLimitResponse;

    const formData = await req.formData();
    const file = formData.get('file') as File | null;
    const kbIdStr = formData.get('kbId') as string | null;

    if (!file || !kbIdStr) {
      return NextResponse.json({ error: 'ZIP File and kbId are required' }, { status: 400, headers: corsHeaders });
    }

    const kbId = parseInt(kbIdStr, 10);
    
    const ownershipError = await requireOwnership('knowledge_base', kbId, user.id);
    if (ownershipError) return ownershipError;

    const buffer = Buffer.from(await file.arrayBuffer());

    // Create the Folder Source
    const newSource = await db.insert(knowledgeSources).values({
      kbId,
      name: file.name,
      type: 'folder',
      classification: { category: 'project', type: 'folder', language: 'mixed' },
      syncStatus: 'syncing'
    }).returning();
    
    const sourceId = newSource[0]!.id;

    // Create a Sync Job
    const syncJob = await db.insert(syncJobs).values({
      sourceId,
      status: 'processing',
      startedAt: new Date()
    }).returning();

    // In a production app, we would process this asynchronously in the background.
    // For V1, we'll process it inline but return early or let it run (Serverless timeout risk).
    // Let's process it synchronously for the prototype.
    const zip = new AdmZip(buffer);
    const zipEntries = zip.getEntries();
    
    let filesProcessed = 0;
    let chunksGenerated = 0;
    let embeddingsGenerated = 0;
    let errorsCount = 0;

    const apiKey = process.env.CKEY_API_KEY || '';

    for (const zipEntry of zipEntries) {
      if (zipEntry.isDirectory || !isProcessableFile(zipEntry.entryName)) {
        continue;
      }

      try {
        const fileBuffer = zipEntry.getData();
        const filename = zipEntry.entryName;
        const fileExtension = filename.split('.').pop()?.toLowerCase() || '';

        // Step 1: Extraction
        // We'll pass a default mimeType based on extension or just application/octet-stream
        const extractedText = await extractTextFromBuffer(fileBuffer, 'application/octet-stream', filename);
        if (!extractedText || extractedText.length < 10) continue;

        // Step 2: Cleaning
        const cleanedText = cleanExtractedText(extractedText);

        // Step 3 & 4: AI Enhancement
        const enhancedData = apiKey ? await enhanceTextWithAI(cleanedText, apiKey, process.env.CKEY_API_URL) : {
          summary: "",
          topics: [],
          keywords: [],
          classification: "Unclassified",
          knowledgeContent: cleanedText,
          embeddingContent: cleanedText
        };

        // Extract relationships
        let relType: 'flutter' | 'dotnet' | 'database' | 'openapi' | 'unknown' = 'unknown';
        if (fileExtension === 'dart') relType = 'flutter';
        else if (fileExtension === 'cs') relType = 'dotnet';
        else if (fileExtension === 'sql') relType = 'database';
        
        const relationships = extractRelationships(cleanedText, relType);

        // Step 5: Save Document
        const newDoc = await db.insert(documents).values({
          kbId,
          sourceId,
          title: filename,
          sourceType: fileExtension || 'unknown',
          sourceUrl: filename,
          content: cleanedText,
          summary: enhancedData.summary,
          topics: enhancedData.topics,
          keywords: enhancedData.keywords,
          classification: enhancedData.classification,
          knowledgeContent: enhancedData.knowledgeContent,
          embeddingContent: enhancedData.embeddingContent,
          sizeBytes: fileBuffer.length,
          metadata: { 
            originalName: filename, 
            processingStrategy: "3-artifact",
            relationships 
          }
        }).returning();

        // Step 6: Chunking
        const chunks = smartChunkMarkdown(enhancedData.embeddingContent || cleanedText);
        chunksGenerated += chunks.length;

        // Step 7: Embeddings
        for (const chunk of chunks) {
          if (chunk.length < 5) continue;
          try {
            const vector = await generateEmbedding(chunk);
            await db.insert(documentChunks).values({
              documentId: newDoc[0]!.id,
              content: chunk,
              embedding: vector
            });
            embeddingsGenerated++;
          } catch (embedErr) {
            console.error("Failed to embed chunk:", embedErr);
          }
        }
        
        filesProcessed++;
      } catch (err) {
        console.error(`Error processing zip entry ${zipEntry.entryName}:`, err);
        errorsCount++;
      }
    }

    // Update Source Statistics & Sync Job
    await db.execute(
      require('drizzle-orm').sql`UPDATE knowledge_sources 
      SET files_processed = files_processed + ${filesProcessed}, 
          chunks_generated = chunks_generated + ${chunksGenerated}, 
          embeddings_generated = embeddings_generated + ${embeddingsGenerated},
          document_count = document_count + ${filesProcessed},
          chunk_count = chunk_count + ${chunksGenerated},
          errors_count = errors_count + ${errorsCount},
          last_sync_at = NOW(),
          last_successful_sync_at = NOW(),
          sync_status = 'success'
      WHERE id = ${sourceId}`
    );

    await db.execute(
      require('drizzle-orm').sql`UPDATE sync_jobs
      SET status = 'completed', finished_at = NOW()
      WHERE id = ${syncJob[0]!.id}`
    );

    return NextResponse.json({ success: true, sourceId, filesProcessed }, { headers: corsHeaders });

  } catch (error: any) {
    console.error('Folder Upload error:', error);
    return NextResponse.json({ error: error.message || 'Failed to process folder' }, { status: 500, headers: corsHeaders });
  }
}
