import { getGlobalConfig } from '@/lib/config';

export default async function PrivacyPage() {
  const config = await getGlobalConfig();

  return (
    <div className="min-h-screen bg-[#020202] text-zinc-300 py-32 px-6 font-sans">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold text-white mb-4">Enterprise Privacy Policy</h1>
        <p className="mb-12 text-zinc-500">Last Updated: {new Date().toLocaleDateString()}</p>
        
        <div className="space-y-10 text-base leading-relaxed text-zinc-400">
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">1. Data Collection & Telemetry</h2>
            <p>GenWorkAI collects essential account telemetry to operate the platform. When you connect databases, GitHub repositories, or document stores to our engine, we extract schemas, text chunks, and metadata necessary to build your intelligent knowledge graph. We do not use your proprietary workspace data to train foundational models across tenants.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">2. Processing of Connected Intelligence</h2>
            <p>Your data remains siloed within your Knowledge Bases. Automated workflows and MCP servers generated by GenWorkAI only process the data you explicitly permit. Vector embeddings generated from your documents are stored securely and used exclusively to serve your REST endpoints and semantic searches.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">3. Security & Encryption</h2>
            <p>We mandate Enterprise-grade security. All database connection strings, API tokens, and access credentials provided to GenWorkAI are encrypted at rest using industry-standard symmetric encryption algorithms. Data in transit is secured via TLS 1.3.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">4. Third-Party Payment Processing</h2>
            <p>We utilize Paddle as our Merchant of Record to handle all financial transactions, invoicing, and subscription management. GenWorkAI does not store or process complete credit card information. Please consult Paddle's Privacy Policy for detailed information on their handling of financial data.</p>
          </section>

          <section className="bg-white/5 border border-white/10 p-8 rounded-2xl mt-12">
            <h2 className="text-xl font-semibold text-white mb-4">Privacy & Data Officer Contact</h2>
            <p className="mb-4">If you require a Data Processing Agreement (DPA) or have questions regarding how we handle your company's intelligence data, please reach out to us:</p>
            <ul className="space-y-2 text-zinc-300">
              <li><strong>Support:</strong> <a href={`mailto:${config.support_email}`} className="text-cyan-400 hover:underline">{config.support_email}</a></li>
              <li><strong>Phone:</strong> {config.phone_number}</li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
}
