import { getGlobalConfig } from '@/lib/config';

export default async function TermsPage() {
  const config = await getGlobalConfig();

  return (
    <div className="min-h-screen bg-[#020202] text-zinc-300 py-32 px-6 font-sans">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold text-white mb-4">Enterprise Terms of Service</h1>
        <p className="mb-12 text-zinc-500">Last Updated: {new Date().toLocaleDateString()}</p>
        
        <div className="space-y-10 text-base leading-relaxed text-zinc-400">
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Enterprise Terms</h2>
            <p>By accessing, subscribing to, or integrating GenWorkAI's knowledge extraction and API generation services into your systems, you agree to be bound by these Terms of Service. This agreement constitutes a legally binding contract between your organization and GenWorkAI.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">2. Description of Platform Capabilities</h2>
            <p>GenWorkAI provides an enterprise intelligence platform that transforms raw data from connected repositories, databases, and documents into accessible Model Context Protocol (MCP) servers and REST endpoints. Usage of the platform is strictly governed by the resource limits associated with your subscribed tier.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">3. Data Security & Artifact Ownership</h2>
            <p>All Workspace Artifacts generated by the platform using your connected sources remain your intellectual property. GenWorkAI does not claim ownership over the SQL queries, PRDs, or architecture diagrams produced for your internal use. You are strictly responsible for ensuring that the underlying data connected to the platform does not violate third-party IP or compliance laws.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">4. Commercial Usage & API Credits</h2>
            <p>Billing is processed via our Merchant of Record (Paddle). Enterprise subscriptions and overage API credits are non-transferable. Sustained utilization of the MCP Builder capabilities requires a valid Pro or Enterprise license. Unauthorized resale of GenWorkAI API endpoints is strictly prohibited.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">5. Limitation of Liability</h2>
            <p>GenWorkAI provides its platform "as-is". Under no circumstances shall GenWorkAI be liable for any indirect, incidental, or consequential damages, including data loss or business interruption resulting from the use of our generated intelligence networks or automation workflows.</p>
          </section>

          <section className="bg-white/5 border border-white/10 p-8 rounded-2xl mt-12">
            <h2 className="text-xl font-semibold text-white mb-4">Contacting Legal & Support</h2>
            <p className="mb-4">For any inquiries regarding these Terms or to report a violation, please contact our enterprise team directly:</p>
            <ul className="space-y-2 text-zinc-300">
              <li><strong>Support Email:</strong> <a href={`mailto:${config.support_email}`} className="text-violet-400 hover:underline">{config.support_email}</a></li>
              <li><strong>Sales Inquiries:</strong> <a href={`mailto:${config.sales_email}`} className="text-violet-400 hover:underline">{config.sales_email}</a></li>
              <li><strong>Phone:</strong> {config.phone_number}</li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
}
